// All editable content lives here. Dummy data, swap freely.
// Covers: set `cover: "assets/name.jpg"` per project (and `img` per process step). Empty = labelled placeholder.
window.SITE = {
  name: "Priya Gupta",
  first: "Priya",
  role: "Product Designer",
  email: "priyagupta0419@gmail.com",
  mailHref: "mailto:priyagupta0419@gmail.com",
  phone: "+91 81693 18881",
  phoneHref: "tel:+918169318881",
  available: true,
  availableNote: "Immediate joiner",
  resume: "assets/Priya_Gupta_Resume.pdf",
  resumeNote: "4 teams, 3+ years, one page.",
  meetNote: "Meet Priya",
  meetSub: "the short version",
  links: [
    { label: "LinkedIn", icon: "linkedin", href: "https://linkedin.com/in/priyaguptaa19" },
    { label: "Behance", icon: "behance", href: "https://behance.net/priyagupta152" },
  ],
  photo: "assets/priya.webp",
  portraitNote: "Thinking about moving pixels…",
  hero: {
    tag: "Product Designer",
    headline: { l1: "I design products", before: "people", circle: "never", after: "think about." },
    sub: "3+ years shipping SaaS, fintech and mobile products. Research‑led, systems‑minded, and fast with AI\u2011assisted design.",
  },
  // handwritten notes around the portrait. x, y in % of the stage; depth = how far it drifts with the mouse.
  notes: [
    { t: "Owns design from discovery to launch", x: 8, y: 30, rot: -6, depth: 0.9 },
    { t: "Order flow cut from 9 steps to 4", x: 70, y: 12, rot: 4, depth: 0.6 },
    { t: "Stockouts down 62% in pilot testing", x: 68, y: 56, rot: -4, depth: 0.8 },
  ],
  cycle: ["research", "design", "test", "ship"], // footer reads: Let’s <one of these> + footerLine
  footerLine: "something incredible together.",
  showSamples: false, // set true to also show the placeholder projects
  work: { title: "Work" },
  photoAbout: "assets/priya.webp",
  about: [
    [
      { t: "I’m drawn to " },
      { t: "systems", tone: "hl" },
      { t: ", the kind where every part has a reason to exist. I studied electrical engineering before design, which is probably why I keep looking for the " },
      { t: "logic behind the screen", tone: "hl" },
      { t: "." },
    ],
    [
      { t: "I like turning " },
      { t: "complex problems", tone: "hl" },
      { t: " into simple products. I start with " },
      { t: "research", tone: "hl" },
      { t: ", build the " },
      { t: "design system", tone: "hl" },
      { t: ", test with real people, and use " },
      { t: "AI tools", tone: "hl" },
      { t: " to move faster without lowering the bar." },
    ],
  ],
  tools: [
    { n: "Figma", icon: "figma", hex: "#F24E1E" },
    { n: "FigJam", icon: "figma", hex: "#A259FF" },
    { n: "Framer", icon: "framer", hex: "#0055FF" },
    { n: "Photoshop", icon: "adobephotoshop", hex: "#31A8FF" },
    { n: "Canva", icon: "canva", hex: "#00C4CC" },
  ],
  experience: [
    { when: "Jul 2025 - Present", role: "Product Designer", where: "Magnumsoft Engineering", result: "Cut a 9-step order flow to 4. Stockouts down 62% in pilot.", stats: [["9 → 4", "order steps"], ["-62%", "stockouts"]] },
    { when: "Jan 2025 - Jun 2025", role: "UI/UX and Graphic Designer", where: "I Dont Blabber", result: "Built the shared Figma component library the team still builds on.", stats: [["1", "shared library"]] },
    { when: "Jan 2024 - Nov 2024", role: "UI/UX Designer", where: "Parshi Technologies", result: "Designed three unrelated consumer apps end to end, all at once.", stats: [["3", "apps at once"]] },
    { when: "Feb 2023 - Dec 2023", role: "Design Intern", where: "CAD Desk", result: "First end-to-end design for a real client: a bakery’s ordering flow.", stats: [["1st", "real client"]] },
  ],
  projects: [
    {
      slug: "virtual-waiter",
      story: "virtual-waiter",
      title: "Virtual Waiter",
      type: "SaaS, multi-role resort operations",
      blurb: "What happens when a \u201Csimple\u201D resort app becomes a system?",
      cover: "assets/projects/virtual-waiter/cover.webp",
      coverAlt: "Collage of resort spaces, people, orders, providers and exceptions around a Villa 12 booking card",
      cardCover: "assets/projects/virtual-waiter/cover-card.webp",
      metric: "3 shifts",
      metricShort: "one model",
      metricLabel: "Space, item and session became the units of the product",
      tint: "coral",
      role: "Product Designer",
      time: "10-12 months",
      collab: "PM, Engineering, QA, Operations",
      focus: "SaaS design, UX, IA, interaction, multi-role system",
    },
    {
      slug: "rentzgo",
      story: "rentzgo",
      title: "RentzGo",
      type: "Rental platform, four roles",
      blurb: "One rental ecosystem for tenants, landlords, service partners and admins.",
      cover: "assets/projects/rentzgo/cover.webp",
      coverAlt: "A tenant, a landlord, a service partner and an admin working together in a bright room under a RentzGo sign",
      metric: "-30%",
      metricShort: "booking steps",
      metricLabel: "fewer steps across key booking flows",
      role: "Product Designer",
      time: "6 months",
      collabLabel: "Scope",
      collab: "Product design, 0 to 1",
      focus: "Research, IA, flows, UI, design system",
    },
    {
      slug: "nexus",
      story: "nexus",
      title: "Nexus",
      type: "AI research workspace, product design",
      blurb: "An AI research workspace connecting context, data, agents and human judgement.",
      cover: "assets/projects/nexus/cover.webp",
      coverAlt: "Three screens of the Nexus research workspace: the entry screen, workflow configuration and the review output",
      metric: "8 modes",
      metricShort: "one research engine",
      metricLabel: "Eight ways to think, one product grammar",
      role: "Product / UX Designer",
      time: "Phase zero",
      collabLabel: "Scope",
      collab: "IA, AI interaction, states",
      focus: "Product thinking, research workspace, failure and review states",
    },
    {
      slug: "cartwise",
      metricShort: "less drop-off",
      tint: "mint",
      sample: true,
      title: "Cartwise",
      type: "Web, e-commerce",
      blurb: "Checkout that people actually finish.",
      cover: "",
      metric: "-27%",
      metricLabel: "checkout drop-off",
      role: "Product designer",
      time: "10 weeks",
      team: "1 PM, 2 devs, 1 analyst",
      tools: "Figma, Hotjar",
      problem: "Grocery shoppers abandoned at the payment step. The form asked for too much, too soon.",
      solution: "A 3-step checkout with saved details, smart defaults and honest delivery slots shown up front.",
      outcome: "Drop-off fell 27%, average checkout time went from 4 minutes to under 2.",
      process: [
        { h: "Audit", p: "Session recordings showed people stalling on address and slot selection.", img: "" },
        { h: "Simplify", p: "Cut 9 fields to 4 and moved account creation after payment.", img: "" },
        { h: "Test", p: "A/B tested two flows on 20% of traffic for two weeks.", img: "" },
        { h: "Scale", p: "Rolled out to all users and added the pattern to the design system.", img: "" },
      ],
      impact: [["-27%", "drop-off"], ["<2 min", "checkout time"], ["+11%", "orders"]],
    },
    {
      slug: "lumen",
      metricShort: "SUS score",
      tint: "butter",
      sample: true,
      title: "Lumen Health",
      type: "Web app, healthcare",
      blurb: "A patient portal that feels human.",
      cover: "",
      metric: "84",
      metricLabel: "SUS score, up from 62",
      role: "UX designer",
      time: "5 months",
      team: "2 designers, 4 devs, clinicians",
      tools: "Figma, Notion",
      problem: "Patients couldn’t find reports or book follow-ups without calling the clinic.",
      solution: "A clear home, plain-language results and one-tap booking, built with clinicians in the loop.",
      outcome: "Usability score rose from 62 to 84. Phone bookings dropped by 40%.",
      process: [
        { h: "Shadow", p: "Spent two days at the clinic watching front desk and patients.", img: "" },
        { h: "Structure", p: "Card sorted 40 features into 5 simple areas.", img: "" },
        { h: "Prototype", p: "Clickable prototype tested with 10 patients, aged 25 to 70.", img: "" },
        { h: "Refine", p: "Large type, high contrast and calmer colour from accessibility review.", img: "" },
      ],
      impact: [["84", "SUS score"], ["-40%", "phone bookings"], ["AA", "accessibility"]],
    },
    {
      slug: "roamly",
      metricShort: "would reuse",
      tint: "periwinkle",
      sample: true,
      title: "Roamly",
      type: "Concept, travel",
      blurb: "Plan a trip with friends without the group chat chaos.",
      cover: "",
      metric: "9/10",
      metricLabel: "testers would use it again",
      role: "Solo designer",
      time: "6 weeks",
      team: "Self-initiated",
      tools: "Figma, Framer",
      problem: "Group trips die in endless chats. Nobody knows what’s decided.",
      solution: "A shared board where ideas become votes, votes become a plan, and the plan becomes a timeline.",
      outcome: "9 out of 10 testers said they’d use it for their next trip.",
      process: [
        { h: "Observe", p: "Read through real group chats (with permission) to spot patterns.", img: "" },
        { h: "Frame", p: "Reduced the problem to “what are we deciding, and who decides”.", img: "" },
        { h: "Build", p: "Made a Framer prototype with voting and live timeline.", img: "" },
        { h: "Learn", p: "Tested with 3 friend groups and rewrote the voting rules twice.", img: "" },
      ],
      impact: [["9/10", "would reuse"], ["3", "groups tested"], ["6 wks", "end to end"]],
    },
  ],
};
